/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocinescliente;

import static Logica.SOUP.service;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class Entradas extends javax.swing.JFrame {

    public static int seleccionada;
    public static int Campos;
    /**
     * Creates new form Entradas
     */
    public Entradas() {
        initComponents();
        this.setLocationRelativeTo(null);
        super.setTitle("Cinepolio");
        String Peliculas = service.listaPeli();
        String[] parts = Peliculas.split("&");
        int size = parts.length;
        for (int i = 0; i < size; i++) {
            this.cmbPeli.addItem(parts[i]);
        }
        this.bmtSeleccionarHora.setEnabled(false);
        this.cmbHora.setEnabled(false);
        this.cmbCantidad.setEnabled(false);
//        this.taNota.setEnabled(false);
        taNota.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNota = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        btmContinuar = new javax.swing.JButton();
        lblBoleteria = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        cmbPeli = new javax.swing.JComboBox<>();
        bmtSeleccionarHora = new javax.swing.JButton();
        cmbHora = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNota1 = new javax.swing.JTextPane();
        lblTotal = new javax.swing.JLabel();
        cmbCantidad = new javax.swing.JComboBox<>();
        fondoblanco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PRECIO DE CADA BOLETO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 190, 20));

        lblInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 130, 20));

        jLabel12.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        jLabel12.setText("Cantidad:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Boletos");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        taNota.setText("Nos reservamos el derecho de admision. En caso de canselacion de la pelicula, no hay ningun tipo de reembolso.");
        taNota.setToolTipText("");
        jScrollPane1.setViewportView(taNota);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 210, 70));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("<-- Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 430, 100, -1));

        btmContinuar.setBackground(new java.awt.Color(153, 153, 255));
        btmContinuar.setText(" CONTINUAR -->");
        btmContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btmContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        lblBoleteria.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblBoleteria.setForeground(new java.awt.Color(255, 255, 255));
        lblBoleteria.setText("BOLETERÍA");
        jPanel1.add(lblBoleteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));
        jPanel1.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, 270));

        cmbPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPeliActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 30));

        bmtSeleccionarHora.setText("Seleccionar");
        bmtSeleccionarHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmtSeleccionarHoraActionPerformed(evt);
            }
        });
        jPanel1.add(bmtSeleccionarHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 30));

        cmbHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHoraActionPerformed(evt);
            }
        });
        jPanel1.add(cmbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 120, 30));

        taNota1.setText("NOTA:  CADA   SALA   TIENE   SUS   ACIENTOS   DEBIDAMENTE   NUMERADOS,   POR   FAVOR   TOMAR   EL   ACIENTO   CORRECTO.");
        taNota1.setToolTipText("");
        jScrollPane2.setViewportView(taNota1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 240, 90));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, 20));

        cmbCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        cmbCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 140, -1));

        fondoblanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Fondo Blanco.jpg"))); // NOI18N
        jPanel1.add(fondoblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 580, 270));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btmContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmContinuarActionPerformed
        Campos = Integer.parseInt(this.cmbCantidad.getSelectedItem().toString());
        Espacios acientos = new Espacios();
        acientos.setVisible(true);; 
        this.dispose();
    }//GEN-LAST:event_btmContinuarActionPerformed

    private void cmbPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeliActionPerformed
        // TODO add your handling code here:
        String Pelicula = cmbPeli.getSelectedItem().toString();
        if (!Pelicula.equals("")) {
            this.bmtSeleccionarHora.setEnabled(true);
            this.cmbHora.setEnabled(true);
            this.cmbHora.removeAllItems();
            String horas = service.buscarPeli(Pelicula);
            String[] parts = horas.split("&");
            int size = parts.length;
            for (int i = 0; i < size; i++) {
                this.cmbHora.addItem(service.getHora(Integer.parseInt(parts[i])) + " Sala " + parts[i]);
            }
        }
    }//GEN-LAST:event_cmbPeliActionPerformed

    private void bmtSeleccionarHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmtSeleccionarHoraActionPerformed
        // TODO add your handling code here:
        if (!cmbHora.getSelectedItem().toString().equals("")) {
            this.cmbCantidad.setEnabled(true);
            String Info = cmbHora.getSelectedItem().toString() + " Sala ";
            String[] parts = Info.split(" Sala ");
            this.seleccionada=Integer.parseInt(parts[1]);
            lblInfo.setText(service.getTipo(this.seleccionada) + "    ₡" + service.getPrecio(this.seleccionada));
        }
    }//GEN-LAST:event_bmtSeleccionarHoraActionPerformed

    private void cmbHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHoraActionPerformed
        // TODO add your handling code here:
        //////////////////////////////////////

    }//GEN-LAST:event_cmbHoraActionPerformed

    private void cmbCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCantidadActionPerformed
        // TODO add your handling code here:
        this.lblTotal.setText("El total a pagar es: ₡"+(service.getPrecio(seleccionada)*Integer.parseInt
                                                        (this.cmbCantidad.getSelectedItem().toString())));
    }//GEN-LAST:event_cmbCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmtSeleccionarHora;
    private javax.swing.JButton btmContinuar;
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<String> cmbPeli;
    private javax.swing.JLabel fondoblanco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBoleteria;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JTextPane taNota;
    private javax.swing.JTextPane taNota1;
    // End of variables declaration//GEN-END:variables
}
