/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocinescliente;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Campos Espinoza
 */
public class Espacios extends javax.swing.JFrame {

    int asientos[][] = new int[6][4];
    ImageIcon x = new ImageIcon("C:\\Users\\Campos Espinoza\\Documents\\NetBeansProjects\\ProyectoCinesCliente\\src\\PNG\\Ocupada.png");
    /**
     * Creates new form Espacios
     */
    public Espacios() {
        initComponents();
        this.setLocationRelativeTo(null);
        super.setTitle("Cinepolio");
       cargar();
    }
    public void cargar(){
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 6; j++) {
                this.asientos[j][i]=1;
            }
        }
        this.asientos[4][2]=0;
        this.asientos[0][0]=0;
        this.asientos[3][3]=0;
        //this.jButton1.setIcon(x);
        this.jButton1.setEnabled(false);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        btmRegresar = new javax.swing.JButton();
        btmContinuar = new javax.swing.JButton();
        lblPantalla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton5.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 50, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton6.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 50, 50));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton7.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, 50));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton8.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, 50));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton9.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 50, 50));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton10.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 50, 50));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 50, 50));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 50, 50));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton13.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 50, 50));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton14.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 50, 50));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton15.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 50, 50));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton16.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 50, 50));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton17.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 50, 50));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton18.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 50));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton19.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, 50));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton20.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 50, 50));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton21.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, 50));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton22.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 50, 50));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton23.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 50, 50));

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Libre.png"))); // NOI18N
        jButton24.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 50, 50));

        btmRegresar.setText("Regresar");
        btmRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btmRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btmContinuar.setText("Continuar");
        btmContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btmContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        lblPantalla.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Pantalla (2).png"))); // NOI18N
        lblPantalla.setText("                      ");
        lblPantalla.setToolTipText("");
        jPanel1.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 450, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmContinuarActionPerformed

    private void btmRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegresarActionPerformed
        Entradas boleteria = new Entradas();
        boleteria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espacios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmContinuar;
    private javax.swing.JButton btmRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPantalla;
    // End of variables declaration//GEN-END:variables
}
